FROM nginx:mainline

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    jq=1.6-2.1 \
    wait-for-it=0.0~git20180723-1 \
  && rm -rf /var/lib/apt/lists/*

COPY packages/app/dist /usr/share/nginx/html

# Add nginx custom pages
COPY packages/app/nginx /usr/share/nginx/html

COPY docker/default.conf.template /etc/nginx/templates/default.conf.template

COPY docker/inject-config.sh /docker-entrypoint.d/40-inject-config.sh

ENV PORT 3000
