frontend:
  baseUrl: http://127.0.0.1:3000

backend:
  baseUrl: http://127.0.0.1:7007
  auth:
    keys:
      - secret: '123456'
  database:
    connection:
      host: db
      user: postgres
      password: postgres
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
auth:
  providers:
    github:
      development:
        clientId: '12345'
        clientSecret: '12345'

proxy:
  '/qa/docserver':
    target: ${DOCSERVER_BASE_URL_QA}
    changeOrigin: true
    pathRewrite:
      '^/api/proxy/qa/docserver/': '/docserver/'
  '/staging/docserver':
    target: ${DOCSERVER_BASE_URL_STAGING}
    changeOrigin: true
    pathRewrite:
      '^/api/proxy/staging/docserver/': '/docserver/'
  '/prod/docserver':
    target: ${DOCSERVER_BASE_URL_PROD}
    changeOrigin: true
    pathRewrite:
      '^/api/proxy/prod/docserver/': '/docserver/'
