version: '3'

services:
  frontend:
    depends_on:
      - backend
    # Waits for the backend to have started and listen on port 7007 before starting
    command: wait-for-it backend:7007 -- ./docker-entrypoint.sh nginx -g "daemon off;"
    build:
      context: ../
      dockerfile: ./Dockerfile.dockerbuild
    volumes:
      - ../:/code
      - node_modules:/code/node_modules
      - app_node_modules:/code/packages/app/node_modules
    ports:
      - '3000:3000'

  backend:
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      AWS_REGION: '${AWS_REGION}'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      DOCSERVER_BASE_URL: '${DOCSERVER_BASE_URL}'
    build:
      context: .
      dockerfile: ./local-Dockerfile
    volumes:
      - ../:/code
      - node_modules:/code/node_modules
      - app_node_modules:/code/packages/app/node_modules
      - backend_node_modules:/code/packages/backend/node_modules
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    ports:
      - '7007:7007'
  #   # Uncomment the next line to use a non-root user for all processes.
  #   # user: node

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

volumes:
  postgres-data:
  node_modules:
  app_node_modules:
  backend_node_modules:
