apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  description: The frontend application for the Lighthouse Developer Portal
  tags:
    - javascript
    - typescript
    - react
  links:
    - url: https://github.com/department-of-veterans-affairs/lighthouse-developer-portal/issues
      title: Issues
      icon: help
    - url: https://department-of-veterans-affairs.github.io/lighthouse-developer-portal/
      title: Docs
      icon: dashboard
    - url: https://backstage.io/
      title: Backstage.io
      icon: web
    - url: https://lighthouseva.slack.com/archives/C020ZR4UL8H
      title: lighthouse-bandicoot slack
      icon: slack
  annotations:
    github.com/project-slug: department-of-veterans-affairs/lighthouse-developer-portal
    datadoghq.com/site: datadoghq.com
    datadoghq.com/dashboard-url: https://p.datadoghq.com/sb/dq828b4kr813cbhm-127a5292a5c6656e73d7ab859c3b46a3
    datadoghq.com/graph-token: f08beb2039525ff568f3de84a9f15e1c3e90f764cd472f280b678513772b3151
spec:
  type: website
  owner: lighthouse-bandicoot
  lifecycle: experimental
  system: lighthouse-developer-portal
  subcomponentOf: lighthouse-developer-portal-monorepo
