name: Deploy to QA Environment
on:
  push:
    tags:
    - '[0-9]+[0-9]+\.[0-9]+[0-9]+\.[0-9]+'
jobs:
  validate-dev-deployment:
    runs-on: ubuntu-latest
    outputs:
      COMMIT_SHA: ${{ steps.main.outputs.COMMIT_SHA }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Get current SHA from Main branch
        id: main
        run: |
          echo "::set-output name=COMMIT_SHA::$(git log -n 1 --format='%H' main)"
      - id: deployment-check
        uses: AminFazlMondo/check-deployed-environment@d81e72d963192276baad035938c30815a1de756f # v1.0.13
        with:
          environment: 'Development'
          commit_sha: ${{ steps.main.outputs.COMMIT_SHA }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: check output
        run: |
          if [[ "${{ steps.deployment-check.outputs.has_active_deployment }}" == "true" ]]; then
            echo -e "Valid Development deployment found"
          else
            echo "No Development Deployment with this commit sha"
            exit 1
          fi
  browser-tests-windows-edge:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/browser-tests
        with:
          browser-name: 'edge'
  deploy-app-qa:
    runs-on: ubuntu-latest
    needs: [validate-dev-deployment, browser-tests-windows-edge]
    environment:
      name: QA
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Deploy app
        uses: ./.github/actions/deploy-backstage-app
        with:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          DOCKERCONFIGJSON: ${{ secrets.DOCKERCONFIGJSON }}
          BACKEND_SECRET: ${{ secrets.BACKEND_SECRET }}
          COMMIT_SHA: ${{ needs.validate-dev-deployment.outputs.COMMIT_SHA }}
          GH_CLIENT_ID: ${{ secrets.GH_OAUTH_CLIENT_ID }}
          GH_CLIENT_SECRET: ${{ secrets.GH_OAUTH_CLIENT_SECRET }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ENV: "qa"
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          DOCSERVER_BASE_URL: ${{ secrets.DOCSERVER_BASE_URL }}
          APP_CREDS_YAML: ${{ secrets.APP_CREDS_YAML }}
          MEMCACHED_USER: ${{ secrets.MEMCACHED_USER }}
          MEMCACHED_PASSWORD: ${{ secrets.MEMCACHED_PASSWORD }}
